---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "*/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
